#############################################################################
# Makefile for building: networksniffer
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sun Oct 21 02:05:18 2012
# Project:  networksniffer.pro
# Template: app
# Command: /home/wheatmai/Programs/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake -spec ../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++ -o Makefile networksniffer.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++ -I. -I../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/include/QtCore -I../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/include/QtGui -I../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/include -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/wheatmai/Programs/QtSDK/Desktop/Qt/4.8.1/gcc/lib
LIBS          = $(SUBLIBS)  -L/home/wheatmai/Programs/QtSDK/Desktop/Qt/4.8.1/gcc/lib -lQtGui -L/home/wheatmai/Programs/QtSDK/Desktop/Qt/4.8.1/gcc/lib -L/usr/X11R6/lib64 -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/wheatmai/Programs/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		capture.cpp \
		cap_optdialog.cpp \
		capthread_data.cpp \
		filter_grammer.cpp moc_mainwindow.cpp \
		moc_capture.cpp \
		moc_cap_optdialog.cpp \
		moc_filter_grammer.cpp
OBJECTS       = main.o \
		mainwindow.o \
		capture.o \
		cap_optdialog.o \
		capthread_data.o \
		filter_grammer.o \
		moc_mainwindow.o \
		moc_capture.o \
		moc_cap_optdialog.o \
		moc_filter_grammer.o
DIST          = ../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/linux.conf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-unix.conf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-unix.conf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/release.prf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		networksniffer.pro
QMAKE_TARGET  = networksniffer
DESTDIR       = 
TARGET        = networksniffer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: networksniffer.pro  ../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++/qmake.conf ../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/linux.conf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-unix.conf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-unix.conf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/release.prf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		/home/wheatmai/Programs/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtGui.prl \
		/home/wheatmai/Programs/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtCore.prl
	$(QMAKE) -spec ../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++ -o Makefile networksniffer.pro
../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf:
../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/linux.conf:
../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf:
../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-unix.conf:
../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf:
../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-unix.conf:
../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri:
../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri:
../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf:
../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf:
../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf:
../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf:
../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/release.prf:
../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf:
../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf:
../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf:
../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf:
../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf:
../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf:
../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf:
../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf:
../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf:
../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf:
../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf:
/home/wheatmai/Programs/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtGui.prl:
/home/wheatmai/Programs/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../../Programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++ -o Makefile networksniffer.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/networksniffer1.0.0 || $(MKDIR) .tmp/networksniffer1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/networksniffer1.0.0/ && $(COPY_FILE) --parents mainwindow.h capture.h packethead.h datatype.h cap_optdialog.h capthread_data.h filter_grammer.h .tmp/networksniffer1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp capture.cpp cap_optdialog.cpp capthread_data.cpp filter_grammer.cpp .tmp/networksniffer1.0.0/ && (cd `dirname .tmp/networksniffer1.0.0` && $(TAR) networksniffer1.0.0.tar networksniffer1.0.0 && $(COMPRESS) networksniffer1.0.0.tar) && $(MOVE) `dirname .tmp/networksniffer1.0.0`/networksniffer1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/networksniffer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_capture.cpp moc_cap_optdialog.cpp moc_filter_grammer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_capture.cpp moc_cap_optdialog.cpp moc_filter_grammer.cpp
moc_mainwindow.cpp: capture.h \
		capthread_data.h \
		cap_optdialog.h \
		filter_grammer.h \
		mainwindow.h
	/home/wheatmai/Programs/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_capture.cpp: capthread_data.h \
		capture.h
	/home/wheatmai/Programs/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) capture.h -o moc_capture.cpp

moc_cap_optdialog.cpp: capture.h \
		capthread_data.h \
		filter_grammer.h \
		cap_optdialog.h
	/home/wheatmai/Programs/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) cap_optdialog.h -o moc_cap_optdialog.cpp

moc_filter_grammer.cpp: capthread_data.h \
		filter_grammer.h
	/home/wheatmai/Programs/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) filter_grammer.h -o moc_filter_grammer.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		capture.h \
		capthread_data.h \
		cap_optdialog.h \
		filter_grammer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		capture.h \
		capthread_data.h \
		cap_optdialog.h \
		filter_grammer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

capture.o: capture.cpp capture.h \
		capthread_data.h \
		packethead.h \
		datatype.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o capture.o capture.cpp

cap_optdialog.o: cap_optdialog.cpp cap_optdialog.h \
		capture.h \
		capthread_data.h \
		filter_grammer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cap_optdialog.o cap_optdialog.cpp

capthread_data.o: capthread_data.cpp capthread_data.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o capthread_data.o capthread_data.cpp

filter_grammer.o: filter_grammer.cpp filter_grammer.h \
		capthread_data.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filter_grammer.o filter_grammer.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_capture.o: moc_capture.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_capture.o moc_capture.cpp

moc_cap_optdialog.o: moc_cap_optdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cap_optdialog.o moc_cap_optdialog.cpp

moc_filter_grammer.o: moc_filter_grammer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filter_grammer.o moc_filter_grammer.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

